//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02_ProductosDefectuosos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res_portugues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res_portugues() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_02_ProductosDefectuosos.Res.portugues", typeof(Res_portugues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acompanhamento.
        /// </summary>
        internal static string Acompanhamento {
            get {
                return ResourceManager.GetString("Acompanhamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adicionar.
        /// </summary>
        internal static string Adicionar {
            get {
                return ResourceManager.GetString("Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adicionar etapas ao rastreamento.
        /// </summary>
        internal static string Adicionar_etapas_ao_rastreamento {
            get {
                return ResourceManager.GetString("Adicionar etapas ao rastreamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajuda.
        /// </summary>
        internal static string Ajuda {
            get {
                return ResourceManager.GetString("Ajuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atualizar.
        /// </summary>
        internal static string Atualizar {
            get {
                return ResourceManager.GetString("Atualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caixa de armazenamento.
        /// </summary>
        internal static string Caixa_de_armazenamento {
            get {
                return ResourceManager.GetString("Caixa de armazenamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código do Produto.
        /// </summary>
        internal static string Código_do_Produto {
            get {
                return ResourceManager.GetString("Código do Produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coluna.
        /// </summary>
        internal static string Coluna {
            get {
                return ResourceManager.GetString("Coluna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condição do produto.
        /// </summary>
        internal static string Condição_do_produto {
            get {
                return ResourceManager.GetString("Condição do produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custo da mão de obra.
        /// </summary>
        internal static string Custo_da_mão_de_obra {
            get {
                return ResourceManager.GetString("Custo da mão de obra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custo da perda de matéria-prima.
        /// </summary>
        internal static string Custo_da_perda_de_matéria_prima {
            get {
                return ResourceManager.GetString("Custo da perda de matéria-prima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custo do Produto.
        /// </summary>
        internal static string Custo_do_Produto {
            get {
                return ResourceManager.GetString("Custo do Produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dados do Produto.
        /// </summary>
        internal static string Dados_do_Produto {
            get {
                return ResourceManager.GetString("Dados do Produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deletar.
        /// </summary>
        internal static string Deletar {
            get {
                return ResourceManager.GetString("Deletar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado do Produto.
        /// </summary>
        internal static string Estado_do_Produto {
            get {
                return ResourceManager.GetString("Estado do Produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excluir.
        /// </summary>
        internal static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar Formulário.
        /// </summary>
        internal static string Finalizar_Formulário {
            get {
                return ResourceManager.GetString("Finalizar Formulário", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gasto Gerado (antes de apresentar defeito).
        /// </summary>
        internal static string Gasto_Gerado__antes_de_apresentar_defeito_ {
            get {
                return ResourceManager.GetString("Gasto Gerado (antes de apresentar defeito)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informações do produto.
        /// </summary>
        internal static string Informações_do_produto {
            get {
                return ResourceManager.GetString("Informações do produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localização Geográfica.
        /// </summary>
        internal static string Localização_Geográfica {
            get {
                return ResourceManager.GetString("Localização Geográfica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string Modificar {
            get {
                return ResourceManager.GetString("Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar produto.
        /// </summary>
        internal static string Modificar_produto {
            get {
                return ResourceManager.GetString("Modificar produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mudar idioma.
        /// </summary>
        internal static string mudar_idioma {
            get {
                return ResourceManager.GetString("mudar idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nível da prateleira.
        /// </summary>
        internal static string Nível_da_prateleira {
            get {
                return ResourceManager.GetString("Nível da prateleira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nome do Produto.
        /// </summary>
        internal static string Nome_do_Produto {
            get {
                return ResourceManager.GetString("Nome do Produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pessoa Responsável.
        /// </summary>
        internal static string Pessoa_Responsável {
            get {
                return ResourceManager.GetString("Pessoa Responsável", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prateleira.
        /// </summary>
        internal static string Prateleira {
            get {
                return ResourceManager.GetString("Prateleira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problema de entrada.
        /// </summary>
        internal static string Problema_de_entrada {
            get {
                return ResourceManager.GetString("Problema de entrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problema Relatado.
        /// </summary>
        internal static string Problema_Relatado {
            get {
                return ResourceManager.GetString("Problema Relatado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantidade de Produtos Danificados.
        /// </summary>
        internal static string Quantidade_de_Produtos_Danificados {
            get {
                return ResourceManager.GetString("Quantidade de Produtos Danificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        internal static string Registrar {
            get {
                return ResourceManager.GetString("Registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relatórios.
        /// </summary>
        internal static string Relatórios {
            get {
                return ResourceManager.GetString("Relatórios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relatórios Financeiros.
        /// </summary>
        internal static string Relatórios_Financeiros {
            get {
                return ResourceManager.GetString("Relatórios Financeiros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relatórios por Gerente.
        /// </summary>
        internal static string Relatórios_por_Gerente {
            get {
                return ResourceManager.GetString("Relatórios por Gerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relatórios por Localização Geográfica.
        /// </summary>
        internal static string Relatórios_por_Localização_Geográfica {
            get {
                return ResourceManager.GetString("Relatórios por Localização Geográfica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsável.
        /// </summary>
        internal static string Responsável {
            get {
                return ResourceManager.GetString("Responsável", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sair.
        /// </summary>
        internal static string Sair {
            get {
                return ResourceManager.GetString("Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salvar.
        /// </summary>
        internal static string Salvar {
            get {
                return ResourceManager.GetString("Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a steps Acompanhamento.
        /// </summary>
        internal static string steps_Acompanhamento {
            get {
                return ResourceManager.GetString("steps Acompanhamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a terminar o upload.
        /// </summary>
        internal static string terminar_o_upload {
            get {
                return ResourceManager.GetString("terminar o upload", resourceCulture);
            }
        }
    }
}
