//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02_ProductosDefectuosos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res_ingles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res_ingles() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_02_ProductosDefectuosos.Res.ingles", typeof(Res_ingles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add steps to tracking.
        /// </summary>
        internal static string Add_steps_to_tracking {
            get {
                return ResourceManager.GetString("Add steps to tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Additional expense.
        /// </summary>
        internal static string Additional_expense {
            get {
                return ResourceManager.GetString("Additional expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Language.
        /// </summary>
        internal static string Change_Language {
            get {
                return ResourceManager.GetString("Change Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Column.
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cost Incurred (before becoming faulty) .
        /// </summary>
        internal static string Cost_Incurred__before_becoming_faulty__ {
            get {
                return ResourceManager.GetString("Cost Incurred (before becoming faulty) ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cost of raw material loss.
        /// </summary>
        internal static string cost_of_raw_material_loss {
            get {
                return ResourceManager.GetString("cost of raw material loss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Damaged Product Quantity .
        /// </summary>
        internal static string Damaged_Product_Quantity_ {
            get {
                return ResourceManager.GetString("Damaged Product Quantity ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Financial Reports.
        /// </summary>
        internal static string Financial_Reports {
            get {
                return ResourceManager.GetString("Financial Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish Form .
        /// </summary>
        internal static string Finish_Form_ {
            get {
                return ResourceManager.GetString("Finish Form ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a finish upload.
        /// </summary>
        internal static string finish_upload {
            get {
                return ResourceManager.GetString("finish upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Follow up.
        /// </summary>
        internal static string Follow_up {
            get {
                return ResourceManager.GetString("Follow up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Follow-up .
        /// </summary>
        internal static string Follow_up_ {
            get {
                return ResourceManager.GetString("Follow-up ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Geographical Location .
        /// </summary>
        internal static string Geographical_Location_ {
            get {
                return ResourceManager.GetString("Geographical Location ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Input problem.
        /// </summary>
        internal static string Input_problem {
            get {
                return ResourceManager.GetString("Input problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Labor cost.
        /// </summary>
        internal static string Labor_cost {
            get {
                return ResourceManager.GetString("Labor cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Out.
        /// </summary>
        internal static string Log_Out {
            get {
                return ResourceManager.GetString("Log Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify.
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify Product.
        /// </summary>
        internal static string Modify_Product {
            get {
                return ResourceManager.GetString("Modify Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product code.
        /// </summary>
        internal static string Product_code {
            get {
                return ResourceManager.GetString("Product code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Code .
        /// </summary>
        internal static string Product_Code_ {
            get {
                return ResourceManager.GetString("Product Code ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a product condition.
        /// </summary>
        internal static string product_condition {
            get {
                return ResourceManager.GetString("product condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Cost .
        /// </summary>
        internal static string Product_Cost_ {
            get {
                return ResourceManager.GetString("Product Cost ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product information.
        /// </summary>
        internal static string Product_information {
            get {
                return ResourceManager.GetString("Product information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Information .
        /// </summary>
        internal static string Product_Information_ {
            get {
                return ResourceManager.GetString("Product Information ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product name.
        /// </summary>
        internal static string Product_name {
            get {
                return ResourceManager.GetString("Product name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Name .
        /// </summary>
        internal static string Product_Name_ {
            get {
                return ResourceManager.GetString("Product Name ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Status .
        /// </summary>
        internal static string Product_Status_ {
            get {
                return ResourceManager.GetString("Product Status ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reported Issue .
        /// </summary>
        internal static string Reported_Issue_ {
            get {
                return ResourceManager.GetString("Reported Issue ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reports by Geographic Location.
        /// </summary>
        internal static string Reports_by_Geographic_Location {
            get {
                return ResourceManager.GetString("Reports by Geographic Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reports by Manager.
        /// </summary>
        internal static string Reports_by_Manager {
            get {
                return ResourceManager.GetString("Reports by Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsible person.
        /// </summary>
        internal static string Responsible_person {
            get {
                return ResourceManager.GetString("Responsible person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsible Person .
        /// </summary>
        internal static string Responsible_Person_ {
            get {
                return ResourceManager.GetString("Responsible Person ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shelf.
        /// </summary>
        internal static string Shelf {
            get {
                return ResourceManager.GetString("Shelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shelf level.
        /// </summary>
        internal static string Shelf_level {
            get {
                return ResourceManager.GetString("Shelf level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steps of Follow-up.
        /// </summary>
        internal static string Steps_of_Follow_up {
            get {
                return ResourceManager.GetString("Steps of Follow-up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Storage bin.
        /// </summary>
        internal static string Storage_bin {
            get {
                return ResourceManager.GetString("Storage bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
