//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02_ProductosDefectuosos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res_español {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res_español() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_02_ProductosDefectuosos.Res.español", typeof(Res_español).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string Actualizar {
            get {
                return ResourceManager.GetString("Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string Ayuda {
            get {
                return ResourceManager.GetString("Ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        internal static string Borrar {
            get {
                return ResourceManager.GetString("Borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Idioma.
        /// </summary>
        internal static string Cambiar_Idioma {
            get {
                return ResourceManager.GetString("Cambiar Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de productos dañada .
        /// </summary>
        internal static string Cantidad_de_productos_dañada_ {
            get {
                return ResourceManager.GetString("Cantidad de productos dañada ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesion .
        /// </summary>
        internal static string Cerrar_Sesion_ {
            get {
                return ResourceManager.GetString("Cerrar Sesion ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a codigo producto.
        /// </summary>
        internal static string codigo_producto {
            get {
                return ResourceManager.GetString("codigo producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código producto .
        /// </summary>
        internal static string Código_producto_ {
            get {
                return ResourceManager.GetString("Código producto ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columna.
        /// </summary>
        internal static string Columna {
            get {
                return ResourceManager.GetString("Columna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo de mano de obra.
        /// </summary>
        internal static string Costo_de_mano_de_obra {
            get {
                return ResourceManager.GetString("Costo de mano de obra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo de mano de obra.
        /// </summary>
        internal static string Costo_de_mano_de_obra1 {
            get {
                return ResourceManager.GetString("Costo de mano de obra1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo de perdida de materia prima.
        /// </summary>
        internal static string Costo_de_perdida_de_materia_prima {
            get {
                return ResourceManager.GetString("Costo de perdida de materia prima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo producto .
        /// </summary>
        internal static string Costo_producto_ {
            get {
                return ResourceManager.GetString("Costo producto ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos del Producto .
        /// </summary>
        internal static string Datos_del_Producto_ {
            get {
                return ResourceManager.GetString("Datos del Producto ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deposito almacenado.
        /// </summary>
        internal static string Deposito_almacenado {
            get {
                return ResourceManager.GetString("Deposito almacenado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado del producto.
        /// </summary>
        internal static string Estado_del_producto {
            get {
                return ResourceManager.GetString("Estado del producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado del producto .
        /// </summary>
        internal static string Estado_del_producto_ {
            get {
                return ResourceManager.GetString("Estado del producto ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estante.
        /// </summary>
        internal static string Estante {
            get {
                return ResourceManager.GetString("Estante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar formulario .
        /// </summary>
        internal static string Finalizar_formulario_ {
            get {
                return ResourceManager.GetString("Finalizar formulario ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gasto adicional.
        /// </summary>
        internal static string Gasto_adicional {
            get {
                return ResourceManager.GetString("Gasto adicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gasto generado (antes de ser defectuoso) .
        /// </summary>
        internal static string Gasto_generado__antes_de_ser_defectuoso__ {
            get {
                return ResourceManager.GetString("Gasto generado (antes de ser defectuoso) ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a informacion producto.
        /// </summary>
        internal static string informacion_producto {
            get {
                return ResourceManager.GetString("informacion producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string Modificar {
            get {
                return ResourceManager.GetString("Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Productos.
        /// </summary>
        internal static string Modificar_Productos {
            get {
                return ResourceManager.GetString("Modificar Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nivel de estante.
        /// </summary>
        internal static string Nivel_de_estante {
            get {
                return ResourceManager.GetString("Nivel de estante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre producto.
        /// </summary>
        internal static string nombre_producto {
            get {
                return ResourceManager.GetString("nombre producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre producto .
        /// </summary>
        internal static string Nombre_producto_ {
            get {
                return ResourceManager.GetString("Nombre producto ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso al seguimiento.
        /// </summary>
        internal static string Paso_al_seguimiento {
            get {
                return ResourceManager.GetString("Paso al seguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a persona responsable.
        /// </summary>
        internal static string persona_responsable {
            get {
                return ResourceManager.GetString("persona responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a problema de entrada.
        /// </summary>
        internal static string problema_de_entrada {
            get {
                return ResourceManager.GetString("problema de entrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problema por el que llega .
        /// </summary>
        internal static string Problema_por_el_que_llega_ {
            get {
                return ResourceManager.GetString("Problema por el que llega ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        internal static string Registrar {
            get {
                return ResourceManager.GetString("Registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte.
        /// </summary>
        internal static string Reporte {
            get {
                return ResourceManager.GetString("Reporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes financieros.
        /// </summary>
        internal static string Reportes_financieros {
            get {
                return ResourceManager.GetString("Reportes financieros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes por responsable.
        /// </summary>
        internal static string Reportes_por_responsable {
            get {
                return ResourceManager.GetString("Reportes por responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes por ubicacion geografica.
        /// </summary>
        internal static string Reportes_por_ubicacion_geografica {
            get {
                return ResourceManager.GetString("Reportes por ubicacion geografica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguimiento.
        /// </summary>
        internal static string Seguimiento {
            get {
                return ResourceManager.GetString("Seguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terminar Carga.
        /// </summary>
        internal static string Terminar_Carga {
            get {
                return ResourceManager.GetString("Terminar Carga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación Geográfica .
        /// </summary>
        internal static string Ubicación_Geográfica {
            get {
                return ResourceManager.GetString("Ubicación Geográfica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación Geográfica .
        /// </summary>
        internal static string Ubicación_Geográfica_ {
            get {
                return ResourceManager.GetString("Ubicación Geográfica ", resourceCulture);
            }
        }
    }
}
